--Criação do usuário
CREATE USER CURSO1 IDENTIFIED BY CURSO1;
--Concedendo permissões para conectar e criar objetos
GRANT CONNECT, RESOURCE, CREATE VIEW TO CURSO1;

CREATE DIRECTORY CURSOSQL as 'C:\ORACLE\DATAPUMP';

CREATE USER CRESCER15 IDENTIFIED BY CRESCER15;

GRANT CONNECT, RESOURCE, CREATE VIEW TO CRESCER15;